config/routes.rb
Rails.application.routes.draw do
  get 'todos/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'todos#index'
  resources :todos, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :update, :destroy]
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path
    else
      render :edit
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end

  def set_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo do |form| %>
  <%= form.text_field :title, placeholder: "タスクを入力する" %>
  <%= form.submit "保存する" %>
<% end %>

app/views/todos/edit.html.erb
<div class="container">
  <h1>タスクの編集</h1>
  <%= render 'form', todo: @todo %>
</div>

app/views/todos/index.html.erb
<div class="container">
  <h1>Todo List</h1>

  <a class="new-task" href="/todos/new">タスクを追加する</a>

  <table>
    <thead>
      <tr>
        <th>タスク</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <% @todos.each do |todo| %>
        <tr>
          <td>
            <%= todo.title %>
          </td>
          <td>
            <%= link_to "編集" , edit_todo_path(todo), class: "edit" %>
              <%= link_to '削除' , todo_path(todo), class: "delete" , data: {turbo_method: :delete,
                turbo_confirm: '本当に削除していいですか?' } %>
          </td>
        </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/todos/new.html.erb
<div class="container">
  <h1>タスクの追加</h1>
  <%= render 'form', todo: @todo %>
</div>